### ISSUE TITLE
element-ui 并不能单独打包

### ISSUE THREAD

**Issue by phtwo** [suyi91/vue-cli3-samples#1]
`/[\\/]node_modules\/element-ui[\\/]/`
改成
`/[\\/]node_modules[\\/]element-ui[\\/]/` 
才行

**Comment by suyi91** [comment]
> `/[\\/]node_modules\/element-ui[\\/]/`
> 改成
> `/[\\/]node_modules[\\/]element-ui[\\/]/`
> 才行

是的 正则有些问题

我修改一下代码
