### ISSUE TITLE
多页面并不是一个好的方案

### ISSUE THREAD

**Issue by lcorz** [suyi91/vue-cli3-samples#2]
就算把page1的引用element-ui删掉 依然还是会在打包完成后的html中引用 css和js都是这样

**Comment by suyi91** [comment]
> 就算把page1的引用element-ui删掉 依然还是会在打包完成后的html中引用 css和js都是这样

在HtmlWebpackPlugin的配置中，设置了`excludeChunks: PAGE_ENTRIES.filter(item => item !== v),`，包含所有chunk(包括elementUI)排除其他page的chunk。

https://github.com/suyi91/vue-cli3-samples/blob/24676d1aaa798d1b810b6bb9f3fd18efeecb886b/vue.config.js.mpa#L27-L36

这个项目的由来是公司一个大多页项目的vue-cli3升级，整体采用了ElementUI所以就如此配置了。

😁感谢反馈
