### ISSUE TITLE
如何去除preload

### ISSUE THREAD

**Issue by weituotian** [suyi91/vue-cli3-samples#3]
打包出来有很多preload
···
  <link href="/css/chunk-theme.5466ba4d.css" rel="preload" as="style">
  <link href="/css/page1.2f0953ce.css" rel="preload" as="style">
  <link href="/css/page2.2f0953ce.css" rel="preload" as="style">
  <link href="/js/chunk-theme.c16a5002.js" rel="preload" as="script">
  <link href="/js/chunk-vendors.7527b935.js" rel="preload" as="script">
  <link href="/js/page1.9d92adbe.js" rel="preload" as="script">
  <link href="/js/page2.5905458d.js" rel="preload" as="script">
  <link href="/css/chunk-theme.5466ba4d.css" rel="stylesheet">
  <link href="/css/page2.2f0953ce.css" rel="stylesheet">
···
网上所有的解决办法都失效了，博主可以良计？

**Comment by suyi91** [comment]
> 打包出来有很多preload
> ···
> 
> ··· 网上所有的解决办法都失效了，博主可以良计？

vue-cli3 提供了`inspect` 可以输出实际的Webpack配置，可以看到`preload`和`prefetch`

```js
/* config.plugin('preload') */
    new PreloadPlugin(
      {
        rel: 'preload',
        include: 'initial',
        fileBlacklist: [
          /\.map$/,
          /hot-update\.js$/
        ]
      }
    ),
    /* config.plugin('prefetch') */
    new PreloadPlugin(
      {
        rel: 'prefetch',
        include: 'asyncChunks'
      }
    ),
```

去除preload只需在vue.config.js配置[chainWebpack](https://cli.vuejs.org/zh/config/#chainwebpack)属性就行了

```js
chainWebpack: config => {
    config.plugins.delete('preload')
  }
```

**Comment by weituotian** [comment]
解决了，多谢博主

**Comment by kaierrao** [comment]
vue配置chunks:all,把js包含进来 。

pages: {
    index: {
      entry: "src/main.js",
      template: "public/index.html",
      filename: "index.html",
      chunks:'all'
    },
