### ISSUE TITLE
打包出来的page1.html和page2.html两者都引入了同样的vendor

### ISSUE THREAD

**Issue by weituotian** [suyi91/vue-cli3-samples#4]
打包出来的page1.html和page2.html两者都引入了这个文件/js/chunk-vendors.7527b935.js
如何让它们引入的vendor不同？

**Comment by suyi91** [comment]
chunk-vendors.js 是用到的node_modules/的打包，能想到的解决方案有两个
1. 配置[splitChunks](https://webpack.js.org/configuration/optimization/)
2. 编译时每次只打包一个page，多次打包可以根据引用的内容生成不同的文件 ^ ^

**Comment by weituotian** [comment]
好，良计
