### ISSUE TITLE
多入口打包到对应文件夹下

### ISSUE THREAD

**Issue by firstmei** [suyi91/vue-cli3-samples#5]
目前多入口是打包到同一个文件夹下的 能打包到对应入口的文件夹下吗

**Comment by suyi91** [comment]
> 目前多入口是打包到同一个文件夹下的 能打包到对应入口的文件夹下吗

建议将多入口的MPA打包改为多次单入口的SPA打包，配置webpack的output和HtmlWebpackPlugin可实现。

MPA打包为一次生成所有，生成的多入口的公用js不方便划分目录。
